name: Daily Zborovi Scrape

on:
  schedule:
    - cron: '15 1 * * *'        # 03:15 Europe/Belgrade (01:15 UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python zborovi_pipeline.py --run

      - name: Generate map
        run: python zborovi_pipeline.py --map

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      - name: Commit & push artifacts
        run: |
          git config user.name "NevenaMijatovic"
          git config user.email "nevena.g.mijatovic@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/NevenaMijatovic/Zborovi.git
          git add zborovi.db zborovi_latest.csv zborovi_map.html
          if git diff-index --quiet HEAD; then
            echo "Nothing new to commit"
          else
            git commit -m "Auto update $(date -u +'%Y-%m-%d %H:%M')"
            git push origin main
          fi
